### ISSUE TITLE
How import SpoutSDK in python? 

### ISSUE THREAD

**Issue by isdzaurov** [spiraltechnica/Spout-for-Python#3]
Hi guys when i run hello.py i get error "import SpoutSDK. How can i import it in python?

**Comment by yuan7407** [comment]
The same issue on python3.7, numpy+opencv+pygame installed, win 10.

**Comment by yuan7407** [comment]
C:\Users\D2C\Downloads\Spout-for-Python-master\Examples>python hello.py
Traceback (most recent call last):
  File "hello.py", line 5, in <module>
    import SpoutSDK
ImportError: DLL load failed: %1

**Comment by Makio64** [comment]
Same error, any lead on it ?

**Comment by Makio64** [comment]
Solved by building boost and then SpoutSDK, the python version have to match else python ignore the .pyd like it doesnt exist..

PS : if you are on visualstudio2017 when you build boost you need to change --toolset=msvc-14.0 to --toolset=msvc-14.1

**Comment by yuan7407** [comment]
@Makio64 thanks for the solution, I switched to python3.5 and reinstalled everything then it works

**Comment by masllsam** [comment]
I have the same issue, downgraded to python 3.5.2 but it didn't work, then I dowgraded to 3.5 but it is still not resolved.. do you have some other suggestions?

**Comment by Hantoo** [comment]
I'm having issues with this. Is it possible to create .pyd files for the common versions?
I'm having issues trying to compile the .dll for my machine.

**Comment by david-sullivan** [comment]
I've had issues updating this to python 3.7. Now VS2017 is looking for python27.lib (???)....
IF anybody has managed to build it for python 3.7, the pyd would be great, or a breakdown of the changes they made in the project. Having spout available in python would be very useful.

**Comment by eps696** [comment]
@david-sullivan @Hantoo 
don't remember where i got it, but here it is 
http://eps.here.ru/work/SpoutSDK37.zip

**Comment by mirabellej** [comment]
Also having this issue with Python 3.6.8. Have tried rebuilding boost and the SpoutSDK. No luck. Anyone have any other suggestions? Alternatives?

**Comment by mirabellej** [comment]
For anyone who is still having trouble getting this to work, try this: https://rusin.work/vjing/tools/spout-for-python/
